[package]
name = "cli"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
easy-repl = "0.2.1" 
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
