[project]
name = "cli"
version="0.1.0"
edition = "2021"

[dependencies]
easy-repl = "0.2.1"
reqwest = { version = "0.11", features = ["json","blocking"] } # reqwest with JSON parsing support
tokio = { version = "1", features = ["full"] }


